language: php

php:
#    - 5.4
#    - 5.5
    - 5.6

before_script:
  - phpenv config-add travis.custom.php.config.ini
  - mysql -e 'create database IF NOT EXISTS symfony;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - cd app/databases && touch test.db3 && cd ../../
  - composer selfupdate
  - composer install
  - php -m | grep lite
  - php app/console doctrine:databa:create --no-interaction --env=test --if-not-exists
  - php app/console doctrine:schema:create --no-interaction --env=test
  - php app/console doctrine:fixtures:load --no-interaction --env=test

script:
  - phpunit -c app --configuration app/phpunit.travis.xml --coverage-text

notifications:
  email:
    -  marcmorales83@gmail.com
    -  david@flux.cat
    -  marc@teclliure.net

branches:
  only:
    - master
    - devel
