services:

    demofony2_admin.gps.type:
        class: Demofony2\AppBundle\Form\Type\Admin\AdminGpsType
        tags:
            - { name: form.type, alias: 'demofony2_admin_gps' }

    demofony2_admin.image.type:
        class: Demofony2\AppBundle\Form\Type\Admin\AdminImageType
        tags:
            - { name: form.type, alias: 'demofony2_admin_image' }

    demofony2_admin.document.type:
        class: Demofony2\AppBundle\Form\Type\Admin\AdminDocumentType
        tags:
            - { name: form.type, alias: 'demofony2_admin_document' }

    sonata.admin.proposal_answer:
        class: Demofony2\AppBundle\Admin\ProposalAnswerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - null
            - Demofony2\AppBundle\Entity\ProposalAnswer
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.document:
        class: Demofony2\AppBundle\Admin\DocumentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Document
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.image:
        class: Demofony2\AppBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false  }
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Image
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.category:
        class: Demofony2\AppBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Participació', label: 'Categoríes'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Category
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.process_participation:
        class: Demofony2\AppBundle\Admin\ProcessParticipationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Participació', label: 'Processos de debat públic'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\ProcessParticipation
            - Demofony2AppBundle:Admin\ProcessParticipation
        calls:
            - [ setTemplate, [edit, :Admin/Edit:customEdit.html.twig]]

    sonata.admin.citizen_forum:
        class: Demofony2\AppBundle\Admin\CitizenForumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Participació', label: 'Fòrums ciutadans'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\CitizenForum
            - Demofony2AppBundle:Admin\CitizenForum
        calls:
            - [ setTemplate, [edit, :Admin/Edit:customEdit.html.twig]]

    sonata.admin.process_participation_page:
        class: Demofony2\AppBundle\Admin\ProcessParticipationPageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\ProcessParticipationPage
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.proposal:
        class: Demofony2\AppBundle\Admin\ProposalAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Participació', label: 'Digues la teva'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Proposal
            - Demofony2AppBundle:Admin\Proposal
        calls:
            - [ setTemplate, [edit, :Admin/Edit:customEdit.html.twig]]

    sonata.admin.cotizen_initiative:
        class: Demofony2\AppBundle\Admin\CitizenInitiativeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Participació', label: 'Iniciatives ciutadanes'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\CitizenInitiative
            - Demofony2AppBundle:Admin\CitizenInitiative
        calls:
            - [ setTemplate, [edit, :Admin/Edit:customEdit.html.twig]]

    sonata.admin.institutional_answer:
        class: Demofony2\AppBundle\Admin\InstitutionalAnswerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - null
            - Demofony2\AppBundle\Entity\InstitutionalAnswer
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.comment:
        class: Demofony2\AppBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Participació', label: 'Comentaris'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Comment
            - Demofony2AppBundle:Admin\Comment

    sonata.admin.calendar:
        class: Demofony2\AppBundle\Admin\CalendarEventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Participació', label: 'Calendari'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\CalendarEvent
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.user:
        class: Demofony2\AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Sistema', label: 'Usuaris'}
        arguments:
            - null
            - Demofony2\UserBundle\Entity\User
            - Demofony2AppBundle:Admin\User
        calls:
            - [ setTemplate, [edit, :Admin/Edit:customEdit.html.twig]]

    sonata.admin.suggestion:
        class: Demofony2\AppBundle\Admin\SuggestionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Sistema', label: 'Suggeriments'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Suggestion
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.page:
        class: Demofony2\AppBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'CMS', label: 'Pàgines'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Page
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.category_transparency:
        class: Demofony2\AppBundle\Admin\CategoryTransparencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Transparència', label: 'Categoria'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\CategoryTransparency
            - 'PixSortableBehaviorBundle:SortableAdmin' # define the new controller via the third argument
        calls:
            - [ setPositionService, [@pix_sortable_behavior.position]]

    sonata.admin.law_transparency:
        class: Demofony2\AppBundle\Admin\LawTransparencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Transparència', label: 'Llei'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\LawTransparency
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.document_transparency:
        class: Demofony2\AppBundle\Admin\DocumentTransparencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Transparència', label: 'Document'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\DocumentTransparency
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.link_transparency:
        class: Demofony2\AppBundle\Admin\LinkTransparencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\LinkTransparency
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.gps:
        class: Demofony2\AppBundle\Admin\GpsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Gps
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.newsletter:
        class: Demofony2\AppBundle\Admin\NewsletterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Newsletter', label: 'Newsletters'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Newsletter
            - Demofony2AppBundle:Admin\Newsletter
