services:
    app.gallery.twig_extension:
        class: Demofony2\AppBundle\Twig\GalleryPathExtension
        public: false
        tags:
            - { name: twig.extension }

    app.image.twig_extension:
        class: Demofony2\AppBundle\Twig\ImagePathExtension
        public: false
        tags:
            - { name: twig.extension }

    app.instanceof.twig_extension:
        class: Demofony2\AppBundle\Twig\InstanceOfExtension
        public: false
        tags:
            - { name: twig.extension }

#    app.calendar_link.twig_extension:
#        class: Demofony2\AppBundle\Twig\CalendarLinkExtension
#        tags:
#          - { name: twig.extension }
#        arguments:
#          - @doctrine.orm.entity_manager
#          - @router
